// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Evently.Modules.Attendance.Infrastructure.Database.Migrations
{
    /// <inheritdoc />
    public partial class Add_EventStatistics : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "event_statistics",
                schema: "attendance",
                columns: table => new
                {
                    event_id = table.Column<Guid>(type: "uniqueidentifier", nullable: false),
                    title = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    description = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    location = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    starts_at_utc = table.Column<DateTime>(type: "datetime2", nullable: false),
                    ends_at_utc = table.Column<DateTime>(type: "datetime2", nullable: true),
                    tickets_sold = table.Column<int>(type: "int", nullable: false),
                    attendees_checked_in = table.Column<int>(type: "int", nullable: false),
                    duplicate_check_in_tickets = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    invalid_check_in_tickets = table.Column<string>(type: "nvarchar(max)", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_event_statistics", x => x.event_id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "event_statistics",
                schema: "attendance");
        }
    }
}
