services:
  evently.api:
    image: evently.api
    container_name: Evently.Api
    depends_on:
      - evently.database
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    volumes:
      - ./.logs/Evently/Dev.Logs:/logs
    ports:
      - "5100:8080"
      - "5101:8081"
  evently.database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: Evently.Database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1234512345Aa$
      - MSSQL_PID=Express
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
  evently.seq:
    image: datalust/seq:latest
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8180:80"
  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: no
    ports:
      - '6379:6379'
  evently.redis.commander:
    container_name: Evently.Redis.Commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: "no"
    environment:
      - REDIS_HOSTS=local:Evently.Redis:6379
    ports:
      - "8181:8081"
  evently.idp.db:
    image: postgres
    container_name: Evently.Idp.Db
    volumes:
      #- ./.containers/database-idp:/var/lib/postgresql/data
      - ./.containers/database-idp:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
  evently.idp:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: Evently.Idp
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=evently-idp-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: -v start-dev
    volumes:
      - ./.files:/opt/keycloak/data/import
      - ./.providers:/opt/keycloak/providers
    ports:
      - "18080:8080"
    depends_on:
      - evently.database
      - evently.idp.db
