name: evently
services:
  evently.api:
    image: evently.api
    container_name: Evently.Api
    depends_on:
      - evently.database
    build:
      context: .
      dockerfile: src/API/Evently.Api/Dockerfile
    #environment:
    #  - OTEL_EXPORTER_OTLP_ENDPOINT=http://evently.jaeger:4317
    volumes:
      - ./.logs/Evently/Dev.Logs:/logs
    ports:
      - "5100:8080"
      - "5101:8081"
  evently.ticketing.api:
    image: eventlyticketing.api
    container_name: Evently.Ticketing.Api
    build:
      context: .
      dockerfile: src/API/Evently.Ticketing.Api/Dockerfile
    #environment:
      #- OTEL_EXPORTER_OTLP_ENDPOINT=http://evently.jaeger:4317
    ports:
      - "5200:8080"
      - "5201:8081"
  evently.gateway:
    image: evently.gateway
    container_name: Evently.Gateway
    build:
      context: .
      dockerfile: src/API/Evently.Gateway/Dockerfile
    #volumes:
    #  - ./.logs/Evently/Dev.Logs:/logs
    ports:
      - "3100:8080"
      - "3101:8081"
  evently.database:
    #image: mcr.microsoft.com/mssql/server:latest
    image: mcr.microsoft.com/mssql/server:2022-CU16-ubuntu-22.04
    container_name: Evently.Database
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1234512345Aa$
      - MSSQL_PID=Express
    volumes:
      - ./.containers/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
  evently.seq:
    image: datalust/seq:2024.3
    container_name: Evently.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:5341"
      - "8180:80" # for monitoring
  evently.redis:
    image: redis:latest
    container_name: Evently.Redis
    restart: no
    ports:
      - '6379:6379'
  evently.redis.commander:
    container_name: Evently.Redis.Commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: "no"
    environment:
      - REDIS_HOSTS=local:Evently.Redis:6379
    ports:
      - "8181:8081"
  evently.idp.db:
    image: postgres
    container_name: Evently.Idp.Db
    volumes:
      #- ./.containers/database-idp:/var/lib/postgresql/data
      - ./.containers/database-idp:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
  evently.idp:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: Evently.Idp
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=evently-idp-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=password
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: -v start-dev
    #--import-realm
    volumes:
      - ./.files/evently-realm-export.json:/opt/keycloak/data/import/realm.json
      - ./.containers/identity:/opt/keycloak/data
    ports:
      - "18080:8080"
    depends_on:
      - evently.database
      - evently.idp.db
  evently.jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: Evently.Jaeger
    ports:
      - "4317:4317" 
      - "4318:4318"
      - "16686:16686" # for monitoring
  evently.queue:
    image: rabbitmq:management-alpine
    container_name: Evently.Queue
    hostname: evently-queue # for connection string
    #volumes:
    #  - ./.containers/queue/data/:/var/lib/rabbitmq
    #  - ./.containers/queue/log/:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672" # for messages
      - "15672:15672" # for monitoring
  evently.mongo:
    image: mongo:8.0.12
    container_name: Evently.Mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./.containers/mongo:/data/db
    ports:
      - "27017:27017"
  evently.mongo.express:
    image: mongo-express
    container_name: Evently.MongoExpress
    #restart: always
    ports:
      - "9781:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@evently.mongo:27017/
      ME_CONFIG_BASICAUTH: false